<?php

namespace AppBundle\Repository;

/**
 * AchievementActionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchievementActionsRepository extends \Doctrine\ORM\EntityRepository
{
}
