<?php

namespace AppBundle\Repository;

/**
 * AdditiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdditiveRepository extends \Doctrine\ORM\EntityRepository
{
}
