<?php

namespace AppBundle\Repository;

/**
 * BudgetThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetThemeRepository extends \Doctrine\ORM\EntityRepository
{
}
