<?php

namespace AppBundle\Repository;

/**
 * BudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BudgetRepository extends \Doctrine\ORM\EntityRepository
{
    // public function findRevenuesByBudget($budgetId)
    // {
    //     return $this->createQueryBuilder('b')
    //         ->select('b', 'm', 'o')
    //         ->from( 'Entity\Budget', 'b' )
    //         ->join( 'Entity\MainRevenue',  'm' )
    //         ->where('m.budget_id = :budgetId')
    //         ->join( 'Entity\OtherRevenue',  'o' )
    //         ->where('o.budget_id = :budgetId')
    //         ->setParameter('budgetId', $budgetId)
    //         ->orderBy('m.date', 'DESC')
    //         // ->setMaxResults(12)
    //         ->getQuery()
    //         ->getResult()
    //     ;
    // }
}
