<?php

namespace AppBundle\Repository;

/**
 * BulkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BulkRepository extends \Doctrine\ORM\EntityRepository
{
}
