<?php

namespace AppBundle\Repository;

/**
 * Categorie_favorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Categorie_favorisRepository extends \Doctrine\ORM\EntityRepository
{

/*
    public function getFavoris($userSlp){
        $favoris = $this->getEntityManager()
            ->createQuery('SELECT f FROM AppBundle:Categorie_favoris f WHERE f.user = :idUser')
            ->setParameter('idUser', $userSlp)
            ->getResult();

        return $favoris;
    }
*/

/*
    public function getFourFavoris($userSlp){
        $favoris = $this->getEntityManager()
            ->createQuery('SELECT f FROM AppBundle:Categorie_favoris f WHERE f.user = :idUser')
            ->setParameter('idUser', $userSlp)
            ->getResult();

        return $favoris;
    }

*/


}
