<?php

namespace AppBundle\Repository;

/**
 * FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedRepository extends \Doctrine\ORM\EntityRepository
{
    /*
    public function getUser($userslp){

        $entityManager = $this->getEntityManager();
        $qb = $entityManager->createQueryBuilder();
        $qb->select('u');
        $qb->from('AppBundle:Feed','u');
        $qb->where('u.user = :idUser');
        $qb->setParameter('idUser',$userslp);

        return $qb;
    }

    */

    public function findByDatePassed($lastlogin)
    {
        $query = $this->createQueryBuilder('feed');
        $query->select('count(feed) as counted');
        $query->where('feed.updateAt > :lastlogin');
        $query->setParameter('lastlogin',$lastlogin);
        return $query->getQuery()->getResult();
    }

}


