<?php

namespace AppBundle\Repository;

/**
 * HiddenSugarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HiddenSugarRepository extends \Doctrine\ORM\EntityRepository
{
}
