<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Budget;

/**
 * MainRevenueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainRevenueRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('date' => 'DESC'));
    }

    public function findByBudget($budgetId)
    {
        return $this->createQueryBuilder('m')
            ->select('m')
            ->from( 'AppBundle\Entity\MainRevenue',  'm' )
            ->where('m.budget_id = :budgetId')
            ->setParameter('budgetId', $budgetId)
            ->orderBy('m.date', 'DESC')
            // ->setMaxResults(12)
            ->getQuery()
            ->getResult()
        ;
    }

    public function findOneByBudget($budgetId)
    {
        return $this->createQueryBuilder('m')
            ->select('m')
            //->from('AppBundle\Entity\MainRevenue',  'm')
            ->where('m.budget = :budgetId')
            ->setParameter('budgetId', $budgetId)
            ->orderBy('m.date', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
        ;
    }

    public function findFirstByBudget($budgetId)
    {
        return $this->createQueryBuilder('m')
            ->select('m')
            //->from('AppBundle\Entity\MainRevenue',  'm')
            ->where('m.budget = :budgetId')
            ->setParameter('budgetId', $budgetId)
            ->orderBy('m.date', 'ASC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();
        ;
    }

    public function findByBudgetAndDates($budgetId, $minDate, $maxDate)
    {
        return $this->createQueryBuilder('m')
            ->select('m')
            //->from( 'AppBundle\Entity\MainRevenue',  'm' )
            ->where('m.budget = :budgetId')
            ->andWhere('m.date >= :minDate')
            ->andWhere('m.date <= :maxDate')
            ->setParameter('budgetId', $budgetId)
            ->setParameter('minDate', $minDate)
            ->setParameter('maxDate', $maxDate)
            ->setMaxResults('1')
            ->getQuery()
            ->getResult();
    }

    public function findPreviousForDate($budgetId, $date) {
        return $this->createQueryBuilder('m')
            ->select('m')
            //->from( 'AppBundle\Entity\MainRevenue',  'm' )
            ->where('m.budget = :budgetId')
            ->andWhere('m.date <= :date')
            ->setParameter('budgetId', $budgetId)
            ->setParameter('date', $date)
            ->orderBy('m.date', 'DESC')
            ->setMaxResults('1')
            ->getQuery()
            ->getOneOrNullResult();
    }

    /*
    public function findMainRevenuesInSameYear($budgetId)
    {
        return $this->createQueryBuilder('m')
            ->select("SUM(m.amount) as a, m.date")
            ->where("m.budget = :budgetId")
            ->setParameter("budgetId" , $budgetId)
            ->groupBy("m.date")
            ->orderBy("m.date", "DESC")
            ->getQuery()
            ->getResult()
            // ->getSingleScalarResult()
        ;
    }
    */
}
