<?php

namespace AppBundle\Repository;

/**
 * MiniprofilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiniprofileRepository extends \Doctrine\ORM\EntityRepository
{    
}
