<?php

namespace AppBundle\Repository;

/**
 * OriginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OriginRepository extends \Doctrine\ORM\EntityRepository
{
}
