<?php

namespace AppBundle\Repository;

/**
 * PackingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PackingRepository extends \Doctrine\ORM\EntityRepository
{
}
