<?php

namespace AppBundle\Repository;

/**
 * PalmOilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PalmOilRepository extends \Doctrine\ORM\EntityRepository
{
}
