<?php

namespace AppBundle\Repository;

/**
 * PersonalisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonalisationRepository extends \Doctrine\ORM\EntityRepository
{
    
}
