<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUserSlpAndCat($userSlpId, $category){
        $query = $this->_em->createQuery(
            'SELECT p 
            FROM AppBundle:Product p 
            JOIN AppBundle:Category c JOIN AppBundle:Subcategory sc JOIN AppBundle:Spending s JOIN AppBundle:UserSlp u 
            WHERE s.userSlp = :userSlpId AND p.subcategory = sc.id AND sc.category = c.id AND c.id = :category');
        $query->setParameter('userSlpId', $userSlpId);
        $query->setParameter('category', $category);
        // $query->setMaxResults('1')
        $results = $query->getResult();
        return $results;
    }

    public function findByUserSlpAndSubcat($userSlpId, $subcategory){
        $query = $this->_em->createQuery(
            'SELECT p 
            FROM AppBundle:Product p 
            JOIN AppBundle:Subcategory sc JOIN AppBundle:Spending s JOIN AppBundle:UserSlp u 
            WHERE p.subcategory = :subcategory AND s.userSlp = :userSlpId AND p.subcategory = sc.id');
        $query->setParameter('userSlpId', $userSlpId);
        $query->setParameter('subcategory', $subcategory);
        // $query->setMaxResults('1')
        $results = $query->getResult();
        return $results;
    }

    public function findByUserSlpAndAlcoolOrTabacCat($userSlpId, $category){
        $query = $this->_em->createQuery(
            'SELECT p 
            FROM AppBundle:Product p 
            JOIN AppBundle:Category c JOIN AppBundle:Spending s JOIN AppBundle:UserSlp u 
            WHERE s.userSlp = :userSlpId AND p.category = c.id AND c.id = :category');
        $query->setParameter('userSlpId', $userSlpId);
        $query->setParameter('category', $category);
        // $query->setMaxResults('1')
        $results = $query->getResult();
        return $results;
    }
}
