<?php

namespace AppBundle\Repository;

/**
 * QualityLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QualityLabelRepository extends \Doctrine\ORM\EntityRepository
{
}
