<?php

namespace AppBundle\Repository;

/**
 * SurveyProgressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyProgressRepository extends \Doctrine\ORM\EntityRepository
{
}
