<?php

namespace AppBundle\Repository;

/**
 * UserProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfilRepository extends \Doctrine\ORM\EntityRepository
{
}
