<?php

namespace AppBundle\Repository;

/**
 * UserProfil_ActionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfil_ActionsRepository extends \Doctrine\ORM\EntityRepository
{
}
