<?php

namespace AppBundle\Repository;

/**
 * UserProfilAchievementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProfilAchievementRepository extends \Doctrine\ORM\EntityRepository
{
}
