<?php

namespace AppBundle\Repository;

/**
 * UserSlpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSlpRepository extends \Doctrine\ORM\EntityRepository
{
    /*
    public function findOneBySomeField($value): ?UserSlp
    {
        return $this->createQueryBuilder('t')
            ->andWhere('t.exampleField = :val')
            ->setParameter('val', $value)
            ->getQuery()
            ->getOneOrNullResult()
        ;
    }
    */

    public function findOneByGaeaUserId($gaeaUserId)
    {
        return $this->createQueryBuilder('u')
        ->andWhere('u.gaeaUserId = :gaeaUserId')
        ->setParameter('gaeaUserId', $gaeaUserId)
        ->getQuery()
        ->getOneOrNullResult();
    }

    public function findAllAnswers($currentUserSlp) {
        $qb = $this->_em
            ->createQueryBuilder()
            ->select('a')
            ->from('AppBundle:Answer', 'a')
            ->where('a.userSlp = :userSlp')
            ->setParameter('userSlp', $currentUserSlp);
        return $qb->getQuery()->getResult();
    }

    public function findUserBudgetRevenue($currentUserSlp) {
        /*$qb = $this->_em
            ->createQueryBuilder()
            ->select('a')
            ->from('AppBundle:Answer', 'a')
            ->where('a.userSlp = :userSlp')
            ->setParameter('userSlp', $currentUserSlp);
        return $qb->getQuery()->getResult();*/
        $query = $this->_em->createQuery('SELECT u, b, m FROM AppBundle:UserSlp u JOIN u.budget b JOIN b.MainRevenue m WHERE a.userSlp = :user');
        $query->setParameter('user', $currentUserSlp);
        $results = $query->getResult();
        return $results;
    }


    /*
    public function getFavoris($id)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->join('categorie_favoris_id', 'f')
            ->where($qb->expr()->eq('f.id', $id));
        return $qb;
    }
    */


}
