<?php

namespace QuestionBundle\Repository;

/**
 * Answer_choiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Answer_choiceRepository extends \Doctrine\ORM\EntityRepository
{

   public function getSubQ($userSlp, $question) {
        return $this->createQueryBuilder('a')
                         ->select('a')
                         ->where('a.userSlp = :userSlp')
                         ->andWhere('a.question = :question')
                         ->setParameter('userSlp', $userSlp)
                         ->setParameter('question', $question)
                         ->getQuery();
     }
}


