<?php

namespace QuestionBundle\Repository;

/**
 * Answer_freeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Answer_freeRepository extends \Doctrine\ORM\EntityRepository
{
   
   /*
   public function FindtrouverAge(){
        
      $em = $entityManager = $this->getEntityManager(); 
      $query = $em->createQuery('SELECT A,U
       FROM QuestionBundle\Entity\Answer_free A 
       JOIN A.userSlp  U  
       WHERE  U.id = 2 ');
 
     return  $query->getResult(); 
   }*/
    
   
}
