<?php

namespace QuestionBundle\Repository;

/**
 * Answer_scaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Answer_scaleRepository extends \Doctrine\ORM\EntityRepository
{
}
