<?php

namespace QuestionBundle\Repository;

/**
 * Conditional_question_choiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Conditional_question_choiceRepository extends \Doctrine\ORM\EntityRepository
{
}
