<?php

namespace QuestionBundle\Repository;

use QuestionBundle\Entity\Conditional_question;

/**
 * Conditional_questionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Conditional_questionRepository extends \Doctrine\ORM\EntityRepository
{  
}
