<?php

namespace QuestionBundle\Repository;

/**
 * Question_masterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Question_masterRepository extends \Doctrine\ORM\EntityRepository
{
}
