<?php

namespace QuestionBundle\Repository;

/**
 * Scale_typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Scale_typeRepository extends \Doctrine\ORM\EntityRepository
{
}
