<?php

namespace QuestionBundle\Repository;

/**
 * Sub_questionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sub_questionRepository extends \Doctrine\ORM\EntityRepository
{
}
