<?php

namespace QuestionBundle\Repository;

/**
 * Sub_question_scaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sub_question_scaleRepository extends \Doctrine\ORM\EntityRepository
{
}
