<?php

namespace QuestionBundle\Repository;

/**
 * Sub_question_freeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sub_question_freeRepository extends \Doctrine\ORM\EntityRepository
{
}
